# Site settings
title: Nathan Hakkakzadeh
baseurl: ""
url: "http://nathancod.es"
timezone: America/Los_Angeles

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

email: hello@nathancod.es

# Excluded files
exclude:
  - Gemfile
  - Gemfile.lock
  - rakefile
  - README.md
  - '*.synctex.gz'
  - '*.log'
  - '*.aux'
  - '*.out'
  - '*.sty'
  - '*.tex'
